org.gradle.jvmargs=-XmxG
org.gradle.parallel=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.0

mod_version=1.0.0
maven_group=fable.codenames
archives_base_name=codenames

fabric_version=0.91.0+1.20.1

local_player_1=Zunserz, af3be95be2544231990a407fd121c1fe
local_player_2=Risha____, 6f71ddddf36248d0af606a601f6b6579
local_player_3=Monolits, 9192f754-5cf4-484e-81bd-9ca5f6519952
local_player_4=Zazelin, 6fba82e8c3d44ab8a635e8f6d1b88766

